"""created chat history model

Revision ID: b16b78442aba
Revises: 11afc3c0b9d8
Create Date: 2025-05-13 06:07:41.514458

"""
from alembic import op
import sqlalchemy as sa
from app.models.base import DateTime

# revision identifiers, used by Alembic.
revision = "b16b78442aba"
down_revision = "11afc3c0b9d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("date_created", DateTime(), nullable=True),
        sa.Column("date_modified", DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_history_id"), "chat_history", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_history_id"), table_name="chat_history")
    op.drop_table("chat_history")
    # ### end Alembic commands ###
