"""initial migration

Revision ID: 3a46a937ff0c
Revises: 
Create Date: 2025-05-12 15:55:50.085652

"""
from alembic import op
import sqlalchemy as sa
from app.models.base import DateTime

# revision identifiers, used by Alembic.
revision = "3a46a937ff0c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "passive", "deleted", name="status"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", DateTime(), nullable=True),
        sa.Column("date_modified", DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
